// A small set of MDI SVG paths; no font, global CSS or network icon lookup.
import {
  mdiAlertCircleOutline,
  mdiArrowLeft,
  mdiArrowRight,
  mdiArrowUp,
  mdiCalendarClock,
  mdiCheckCircleOutline,
  mdiChevronDown,
  mdiChevronRight,
  mdiChevronUp,
  mdiClose,
  mdiCloudAlertOutline,
  mdiCloudCheckOutline,
  mdiCodeJson,
  mdiCogOutline,
  mdiConnection,
  mdiContentSaveOutline,
  mdiEyeOffOutline,
  mdiEyeOutline,
  mdiFileKeyOutline,
  mdiFileSearchOutline,
  mdiFolderCogOutline,
  mdiFolderOpenOutline,
  mdiFolderOutline,
  mdiFolderPlusOutline,
  mdiFolderSearchOutline,
  mdiMagnify,
  mdiMovieOutline,
  mdiPlayOutline,
  mdiPlus,
  mdiRefresh,
  mdiStopCircleOutline,
  mdiTelevisionClassic,
  mdiTrashCanOutline,
  mdiTune,
  mdiTuneVariant,
} from "@mdi/js";

export const icons = {
  mdiAlertCircleOutline: [mdiAlertCircleOutline],
  mdiArrowLeft: [mdiArrowLeft],
  mdiArrowRight: [mdiArrowRight],
  mdiArrowUp: [mdiArrowUp],
  mdiCalendarClock: [mdiCalendarClock],
  mdiCheckCircleOutline: [mdiCheckCircleOutline],
  mdiChevronDown: [mdiChevronDown],
  mdiChevronRight: [mdiChevronRight],
  mdiChevronUp: [mdiChevronUp],
  mdiClose: [mdiClose],
  mdiCloudAlertOutline: [mdiCloudAlertOutline],
  mdiCloudCheckOutline: [mdiCloudCheckOutline],
  mdiCodeJson: [mdiCodeJson],
  mdiCogOutline: [mdiCogOutline],
  mdiConnection: [mdiConnection],
  mdiContentSaveOutline: [mdiContentSaveOutline],
  mdiEyeOffOutline: [mdiEyeOffOutline],
  mdiEyeOutline: [mdiEyeOutline],
  mdiFileKeyOutline: [mdiFileKeyOutline],
  mdiFileSearchOutline: [mdiFileSearchOutline],
  mdiFolderCogOutline: [mdiFolderCogOutline],
  mdiFolderOpenOutline: [mdiFolderOpenOutline],
  mdiFolderOutline: [mdiFolderOutline],
  mdiFolderPlusOutline: [mdiFolderPlusOutline],
  mdiFolderSearchOutline: [mdiFolderSearchOutline],
  mdiMagnify: [mdiMagnify],
  mdiMovieOutline: [mdiMovieOutline],
  mdiPlayOutline: [mdiPlayOutline],
  mdiPlus: [mdiPlus],
  mdiRefresh: [mdiRefresh],
  mdiStopCircleOutline: [mdiStopCircleOutline],
  mdiTelevisionClassic: [mdiTelevisionClassic],
  mdiTrashCanOutline: [mdiTrashCanOutline],
  mdiTune: [mdiTune],
  mdiTuneVariant: [mdiTuneVariant],
};
